---
# tasks file for pipoe2h.pivpn

- name: Check if OpenVPN HMAC key exists
  stat:
    path: "{{ easyrsa.directory }}/keys/ta.key"
  register: openvpnhmac

- name: Generate the static HMAC key
  shell: openvpn --genkey --secret ta.key
  args:
    executable: /bin/bash
    chdir: "{{ easyrsa.directory }}/keys"
  when: openvpnhmac.stat.exists == False
- name: Copy OpenVPN server.conf file
  template:
    src: "{{ role_path }}/templates/openvpn_server.conf.j2"
    dest: /etc/openvpn/server.conf
    mode: 0644
    owner: root
    group: root
  notify: restart openvpn

- name: Enable packet forwarding for IPv4
  replace:
    dest: /etc/sysctl.conf
    regexp: '#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'
  register: sysctl

- name: Run sysctl
  shell: sysctl -p
  when: sysctl.changed

- name: Create OpenVPN firewall rule to allow Internet through the VPN connection
  template:
    src: "{{ role_path }}/templates/firewall-openvpn-rules.sh.j2"
    dest: /etc/firewall-openvpn-rules.sh
    mode: 0700
    owner: root
    group: root

- name: Enable OpenVPN firewall rule execution in the network interface
  lineinfile:
    dest: /etc/network/interfaces
    insertafter: '^iface eth0'
    line: ' pre-up /etc/firewall-openvpn-rules.sh'
  notify: restart networking
